# Generated by Django 5.1.7 on 2025-05-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
