# Generated by Django 5.1.7 on 2025-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transportationrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationrequest',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
