# Generated by Django 5.1.7 on 2025-03-09 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_end_date_activity_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_date',
        ),
    ]
