# Generated by Django 5.1.7 on 2025-05-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealselection',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
