# Generated by Django 5.1.7 on 2025-04-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_activityinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
