# Generated by Django 5.1.7 on 2025-05-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activity_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='resident_name',
        ),
        migrations.RemoveField(
            model_name='mealselection',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='mealselection',
            name='resident_name',
        ),
        migrations.RemoveField(
            model_name='mealselection',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealselection',
            name='allergies',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mealselection',
            name='drinks',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mealselection',
            name='guest_meal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealselection',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealselection',
            name='main_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealselection',
            name='protein',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealselection',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealselection',
            name='room_service',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_allergies', models.TextField(blank=True, default='')),
                ('default_guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('default_guest_meal', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
