# Generated by Django 5.1.7 on 2025-05-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dailymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
    ]
