# Generated by Django 5.1.7 on 2025-05-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='List of menu items'),
        ),
    ]
