# Generated by Django 5.1.7 on 2025-05-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_dailymenu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
